inherit_from:
  .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'features/**/*'

Metrics/LineLength:
  Max: 350

Lint/UnusedBlockArgument:
    Enabled: false

AllCops:
  TargetRubyVersion: 2.3
