inherit_from:
  .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'features/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 350

Lint/UnusedBlockArgument:
    Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
