inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
inherit_from:
  .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'features/**/*'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 90
  Exclude:
    - 'spec/**/*'

# Sometimes we want to have if blocks and not just "method_call if condition"
Style/GuardClause:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/LineLength:
  Max: 350

# Imo if not is more readable than unless
Style/NegatedIf:
  Enabled: false

# Allow "if not condition" instead of requiring "if !condition"
Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'spec/support/locale_fix.rb'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword
  AutoCorrect: true

Layout/ElseAlignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

# Ability excludes
Style/SymbolArray:
  Exclude:
    - 'app/abilities/*'
    - 'spec/abilities/*'

Style/RedundantSelf:
  Exclude:
    - 'app/abilities/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes