inherit_from:
  .rubocop_todo.yml

AllCops:
  Excludes:
    - 'db/**'
    - 'config/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'features/**/*'

Metrics/LineLength:
  Max: 350

Lint/UnusedBlockArgument:
    Enabled: false

AllCops:
  TargetRubyVersion: 2.3

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
