require: rubocop-rspec

inherit_from:
  .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'features/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 350

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/UnusedBlockArgument:
    Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
RSpec/FilePath:
  Exclude:
    - spec/**/*

# RSpec <3
AllCops:
  RSpec:
    Patterns:
      #- _spec.rb
      - _factory.rb
      - ability_spec.rb


  RSpec/FactoryBot:
    Patterns:
      - spec/factories/**/*.rb

