language: ruby

rvm:
    - 2.1.5

services:
    postgresql

before_install:
    - make copy-config-files
    - make copy-travis-files
    - psql -c 'create database travis_test;' -U postgres

install:
    - make

script:
    - make test

notifications:
      email: false
