version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: samfundet
      POSTGRES_PASSWORD: samfundet
    ports:
      - "127.0.0.1:5432:5432"
  
  app:
    build: .
    volumes:
      - .:/Samfundet # Share project code between host machine and container to enable reload on changes.
    environment:
      POSTGRES_USER: samfundet
      POSTGRES_PASSWORD: samfundet
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"
